apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hickory-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hickory.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: hickory-ui
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: control-api
                port:
                  number: 8080
